feat: migrate private module
terraform-ibm-modules/terraform-ibm-icd-redis pull request #188
Opened 2023-07-11 11:48 UTC by jor2

### Description
https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/issues/187

### Types of changes in this PR
Migrating private module to public domain.

#### Changes that affect the core Terraform module or submodules
- [ ] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-07-11 11:58 UTC, jor2 commented
/run_pipeline

2023-07-11 12:00 UTC, jor2 commented
/run pipeline

2023-07-11 12:11 UTC, jor2 commented
/run pipeline

2023-07-11 12:13 UTC, jor2 commented
/run pipeline

2023-07-11 12:21 UTC, jor2 commented
Need to skip upgrade test, as previous branch tries to call master branch which doesn't exist.

2023-07-11 12:24 UTC, jor2 commented
/run pipeline

2023-07-11 13:15 UTC, ocofaigh requested changes
see comments

2023-07-11 13:15 UTC, ocofaigh commented on README.md
> +## Compliance and security
This whole section (Compliance and security) needs to be removed for public

2023-07-11 13:15 UTC, ocofaigh commented on README.md
> +  source            = "git::https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis?ref=main"
Can you update this to the hashicorp syntax (It will be published to hashicorp as soon as we have the first release)

2023-07-11 13:15 UTC, ocofaigh commented on examples/basic/main.tf
> +  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-resource-group.git?ref=v1.0.5"
please use the hashicorp syntax

2023-07-11 13:15 UTC, ocofaigh commented on examples/complete/main.tf
> +  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-resource-group.git?ref=v1.0.5"
update to hashicorp syntax

2023-07-11 13:15 UTC, ocofaigh commented on examples/fscloud/main.tf
> +  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-resource-group.git?ref=v1.0.5"
update to use hashicorp syntax

2023-07-11 13:15 UTC, ocofaigh commented on profiles/fscloud/README.md
> +The default values in this profile were scanned by [IBM Code Risk Analyzer (CRA)](https://cloud.ibm.com/docs/code-risk-analyzer-cli-plugin?topic=code-risk-analyzer-cli-plugin-cra-cli-plugin#terraform
`goals with one exception` -> `rules with one exception`

2023-07-11 13:15 UTC, ocofaigh commented on profiles/fscloud/README.md
> +> 3000210: Check whether Databases for Redis network access is restricted to specific IP range.
This is referencing a goal ID. We have moved to rules now, so you need to reference the rule ID

2023-07-11 13:15 UTC, ocofaigh commented on tests/go.mod
> +	github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper v1.8.11
these are old versions. Please put back to the latest

2023-07-11 13:15 UTC, ocofaigh commented on tests/pr_test.go
> +			"redis_version": "6", // Locking this to version 6 as users block is not supported in <6 Redis versions.
Hmm, not sure about that comment. Its locked into 6 because we have tests to cover all other support versions (5 and 6.2)

2023-07-12 02:09 UTC, jor2 commented
/run pipeline

2023-07-12 08:46 UTC, ocofaigh commented on main.tf
> +  tags                 = var.tags
This is a bug that was spotted yesterday across ICD modules. Resource key tagging is not actually supported by IBM Cloud. The provider doc actually says this:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/assets/29608224/82592059-9d6d-4f53-8809-df43f48992c0)

So I think remove the tags attribute from this block here, and also update the variable description for `tags` so it doesn't mention service credentials.

2023-07-12 08:47 UTC, ocofaigh commented on variables.tf
> +  description = "Optional list of tags to be added to the Redis instance and the associated service credentials (if creating)."
Update to just say: `Optional list of tags to be added to the Redis instance` (see https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/pull/188/files#r1260832608)

2023-07-13 11:12 UTC, ocofaigh commented
/run pipeline

2023-07-13 11:32 UTC, ocofaigh requested changes
@jor2 please address failing precommit

2023-07-13 12:34 UTC, jor2 commented
/run pipeline

2023-07-13 13:51 UTC, ocofaigh approved these changes

2023-07-13 13:51 UTC, merged